# Site settings
title: Jacek Styrylski
header-img: img/home.jpg
email: jacek.styrylski@gmail.com
copyright_name: henioStraszny - Jacek Styrylski
description: "I’m a Software Developer who is enthusiastic about IT in any form."
#baseurl: "/startbootstrap-clean-blog-jekyll"
url: http://jacekstyrylski.github.io
twitter_username: JStyrylski
github_username: henioStraszny
#facebook_username:  StartBootstrap
email_username: jacek.styrylski@gmail.com

# Google Analytics
google_tracking_id: UA-92553181-1

# Build settings
markdown: kramdown
# highlighter: rouge
kramdown:
 syntax_highlighter: rouge
 syntax_highlighter_opts:
   css_class: 'highlight'
#    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
   span:
     line_numbers: false
   block:
     line_numbers: true
     start_line: 1 
#
#      kramdown.syntax_highlighter_opts.block.line_numbers = true
#     input: GFM
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
