# Site settings
title: Jacek Styrylski
header-img: img/home.jpg
email: jacek.styrylski@gmail.com
copyright_name: henioStraszny - Jacek Styrylski
description: "I’m a Software Developer who is enthusiastic about IT in any form."
#baseurl: "/startbootstrap-clean-blog-jekyll"
url: http://jacekstyrylski.github.io
twitter_username: JStyrylski
github_username: henioStraszny
#facebook_username:  StartBootstrap
email_username: jacek.styrylski@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-92553181-1

# Build settings
# markdown: kramdown
# highlighter: rouge
# kramdown:
#     input: GFM
#     syntax_highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
